[workspace]
members = [
    "glutin",
    "glutin_examples",
    "glutin_egl_sys",
    "glutin_glx_sys",
    "glutin_wgl_sys",
    "glutin_gles2_sys",
]

[replace]
"glutin_egl_sys:0.1.2" = { path = "glutin_egl_sys" }
"glutin_glx_sys:0.1.2" = { path = "glutin_glx_sys" }
"glutin_wgl_sys:0.1.2" = { path = "glutin_wgl_sys" }
"glutin_gles2_sys:0.1.2" = { path = "glutin_gles2_sys" }

