[workspace]
members = [
    "glutin",
    "glutin_lighter",
    "glutin_examples",
    "glutin_examples/ios-example/rust",
    "glutin_egl_sys",
    "glutin_glx_sys",
    "glutin_wgl_sys",
    "glutin_gles2_sys",
]

[replace]
"winit:0.20.0-alpha2" = { path = "../winit" }
