[package]
name = "glutin_examples"
version = "0.1.2"
authors = ["The glutin contributors", "Hal Gentz <zegentzy@protonmail.com>"]
description = "Examples for glutin"
repository = "https://github.com/rust-windowing/glutin"
license = "Apache-2.0"
readme = "../README.md"
build = "build.rs"
edition = "2018"
publish = false

[dependencies]
glutin = { path = "../glutin" }
glutin_lighter = { path = "../glutin_lighter" }
winit = "0.19"
takeable-option = "0.5"
image = "0.21"
env_logger = "0.6"

[build-dependencies]
gl_generator = "0.11"
