name: Publish

on:
  push:
    branches: [master]
    paths: 
     - '**/Cargo.toml'
     - '.github/workflows/publish.yml'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        components: rustfmt
    - name: Publish to crates.io
      run: |
        cd glutin && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
        cd glutin_egl_sys && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
        cd glutin_emscripten_sys && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
        cd glutin_gres2_sys && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
        cd glutin_glx_sys && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
        cd glutin_wgl_sys && cargo publish --token ${{ secrets.cratesio_token }} && cd ..
